version: '3.7'

services:
  plex:
    container_name: plex
    image: "plexinc/pms-docker:${TAG}"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP} 
    volumes:
      - config:/config
      - transcode:/transcode
      - ${DATAPATH}:/data
    mac_address: ${MAC}
    networks:
      # Network name of the macvlan to use 
      mexique_docker:
        ipv4_address: ${PRIVATEIP}

volumes:
  transcode:
  config:

networks:
  mexique_docker:
    # Tell the macvlan already created
    external: true
