version: '3.7'

services:
  plex:
    container_name: plex
    image: "plexinc/pms-docker:${TAG}"
    restart: unless-stopped
    environment:
      - TZ='America/Toronto'
      - PLEX_CLAIM=claim-p8a7zZrBvP4ui6j4P4XM
      - ADVERTISE_IP=http://home.guidetutoriel.com:32400/
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp     
    volumes:
      - config:/config
      - transcode:/transcode
      - ${DATAPATH}:/data

volumes:
  transcode:
  config:
