version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /mnt/iscsi/docker/minecraft:/data